import unittest

from playbookos.ui import build_dashboard_html


class DashboardHtmlTestCase(unittest.TestCase):
    def test_dashboard_html_includes_workbench_bilingual_toggle_and_new_resources(self) -> None:
        html = build_dashboard_html(
            {
                "goals": {"draft": 1, "blocked": 2},
                "playbooks": {"compiled": 1},
                "knowledge_bases": {"draft": 2},
                "knowledge_updates": {"proposed": 1},
                "tasks": {"ready": 3},
                "runs": {"waiting_human": 1, "succeeded": 5},
                "acceptances": {"accepted": 1},
                "artifacts": {"run_report": 4},
                "reflections": {"proposed": 2, "published": 1},
            }
        )

        self.assertIn("PlaybookOS 控制台", html)
        self.assertIn("PlaybookOS Console", html)
        self.assertIn('id="lang-zh"', html)
        self.assertIn('id="lang-en"', html)
        self.assertIn('localStorage.getItem(\'playbookos-language\')', html)
        self.assertIn('data-i18n="workbench_title"', html)
        self.assertIn('id="goal-form"', html)
        self.assertIn('id="sop-ingest-form"', html)
        self.assertIn('id="playbook-form"', html)
        self.assertIn('id="knowledge-form"', html)
        self.assertIn('id="mcp-server-form"', html)
        self.assertIn('id="task-form"', html)
        self.assertIn('id="ingest-guidance"', html)
        self.assertIn('id="ingest-playbook-file-input"', html)
        self.assertIn('id="editor-resource-type"', html)
        self.assertIn('id="editor-resource-id"', html)
        self.assertIn('id="editor-payload-input"', html)
        self.assertIn('id="action-status"', html)
        self.assertIn('id="goal-action-rows"', html)
        self.assertIn('id="review-action-rows"', html)
        self.assertIn('id="learning-action-rows"', html)
        self.assertIn('id="supervisor-summary-rows"', html)
        self.assertIn('renderSupervisorCenter()', html)
        self.assertIn('aggregateForGoal(goal)', html)
        self.assertIn('supervisor_center_arbitration', html)
        self.assertIn('supervisor_center_recommendations', html)
        self.assertIn('session_role_label', html)
        self.assertIn('id="session-groups"', html)
        self.assertIn('id="execution-inspector-rows"', html)
        self.assertIn('id="authoring-wizard-rows"', html)
        self.assertIn('renderExecutionInspector()', html)
        self.assertIn('id="route-focus-section"', html)
        self.assertIn('id="route-detail-section"', html)
        self.assertIn('id="dashboard-alerts-section"', html)
        self.assertIn('id="dashboard-blocker-rows"', html)
        self.assertIn('id="dashboard-recommendation-rows"', html)
        self.assertIn('renderDashboardAlerts()', html)
        self.assertIn('dashboard_blockers_title', html)
        self.assertIn('id="dashboard-tasks-section"', html)
        self.assertIn('id="dashboard-learning-section"', html)
        self.assertIn('id="dashboard-active-task-rows"', html)
        self.assertIn('id="dashboard-learning-feed-rows"', html)
        self.assertIn('renderDashboardTaskSections()', html)
        self.assertIn('renderDashboardLearningSections()', html)
        self.assertIn('dashboard_active_tasks_title', html)
        self.assertIn('dashboard_learning_feed_title', html)
        self.assertIn('id="global-scope-value-select"', html)
        self.assertIn('topbar_scope_value_label', html)
        self.assertIn('topbar_scope_value_all', html)
        self.assertIn('applyGlobalScope(', html)
        self.assertIn('scopeOptions(kind)', html)
        self.assertIn('filterResourcesByScope(resources)', html)
        self.assertIn('deriveSnapshotFromResources(resources)', html)
        self.assertIn('dashboard_recommendations_title', html)
        self.assertIn('id="route-detail-rows"', html)
        self.assertIn('renderRouteDetails()', html)
        self.assertIn("mcp: ['route-focus-section', 'route-detail-section', 'workbench-section', 'editor-section']", html)
        self.assertIn("knowledge: ['route-focus-section', 'route-detail-section', 'workbench-section', 'editor-section']", html)
        self.assertIn("tasks: ['route-focus-section', 'route-detail-section', 'workbench-section', 'editor-section', 'action-center-section']", html)
        self.assertIn('route_mcp_registry_title', html)
        self.assertIn('route_knowledge_entries_title', html)
        self.assertIn('route_task_queue_title', html)
        self.assertIn('route_sessions_timeline_title', html)
        self.assertIn('route_learning_pipeline_title', html)
        self.assertIn('renderSettingsPanels()', html)
        self.assertIn('renderModelSettingsForm()', html)
        self.assertIn("fetchJson('runtime-settings')", html)
        self.assertIn("putJson('runtime-settings'", html)
        self.assertIn('id="model-settings-rows"', html)
        self.assertIn('id="model-settings-base-url-input"', html)
        self.assertIn('id="model-settings-model-input"', html)
        self.assertIn('id="model-settings-api-key-input"', html)
        self.assertIn('id="model-settings-save-button"', html)
        self.assertIn('model_settings_status_saved', html)
        self.assertIn('id="global-settings-rows"', html)
        self.assertIn('id="global-settings-default-language-input"', html)
        self.assertIn('id="global-settings-save-button"', html)
        self.assertIn('global_settings_status_saved', html)
        self.assertIn('id="session-admin-rows"', html)
        self.assertIn('id="session-admin-session-select"', html)
        self.assertIn('id="session-admin-save-button"', html)
        self.assertIn('session_admin_status_saved', html)
        self.assertIn('runtimeGlobalSettings()', html)
        self.assertIn('syncAutoRefreshTimer()', html)
        self.assertIn('putJson(`sessions/${sessionAdminSessionId}`', html)
        self.assertIn("sessions: ['route-focus-section', 'route-detail-section', 'session-tree-section', 'execution-inspector-section', 'supervisor-section']", html)
        self.assertIn("learning: ['route-focus-section', 'route-detail-section', 'patch-review-section', 'skill-version-section', 'supervisor-section']", html)
        self.assertIn("'session-admin': ['settings-placeholder-section', 'route-detail-section', 'session-tree-section']", html)
        self.assertIn('id="route-focus-rows"', html)
        self.assertIn('renderRouteFocus()', html)
        self.assertIn("playbooks: ['route-focus-section', 'workbench-section', 'patch-review-section', 'editor-section']", html)
        self.assertIn("approvals: ['route-focus-section', 'action-center-section']", html)
        self.assertIn("const sectionNames = currentRoute", html)
        self.assertIn("? sectionOrder", html)
        self.assertIn('routeResourceSections(currentRoute)', html)
        self.assertIn('renderIngestionGuidance()', html)
        self.assertIn('renderSkillAuthoringWizard()', html)
        self.assertIn('markMaterializedSkill(result)', html)
        self.assertIn('execution_inspector_title', html)
        self.assertIn('renderSessionTree()', html)
        self.assertIn('session-node-children', html)
        self.assertIn('id="patch-review-rows"', html)
        self.assertIn('renderPatchReviews()', html)
        self.assertIn('patch-change', html)
        self.assertIn('id="skill-version-rows"', html)
        self.assertIn('renderSkillVersions()', html)
        self.assertIn('action_create_skill_version', html)
        self.assertIn('action_rollback_skill', html)
        self.assertIn("actionButton('action_autopilot'", html)
        self.assertIn("postJson(`knowledge-updates/${actionTarget}/${actionName}`", html)
        self.assertIn("postJson(`tasks/${actionTarget}/accept`", html)
        self.assertIn('resourcePaths = {"goals": "goals"', html)
        self.assertIn('"mcp_servers": "mcp-servers"', html)
        self.assertIn('"knowledge_bases": "knowledge-bases"', html)
        self.assertIn('"knowledge_updates": "knowledge-updates"', html)
        self.assertIn("postJson('knowledge-bases'", html)
        self.assertIn("postJson('mcp-servers'", html)
        self.assertIn("knowledge_updates", html)
        self.assertIn("postJson('playbooks/import'", html)
        self.assertIn("postJson('playbooks/ingest'", html)
        self.assertIn('ingest_source_saved', html)
        self.assertIn('ingest_tooling_summary', html)
        self.assertIn('ingest_tooling_existing_mcp', html)
        self.assertIn('ingest_tooling_prompts', html)
        self.assertIn('result.tooling_guidance', html)
        self.assertIn('tooling.prompt_blocks', html)
        self.assertIn("action_create_mcp_draft", html)
        self.assertIn("playbooks/${actionTarget}/mcp-drafts", html)
        self.assertIn('ingest_source_view', html)
        self.assertIn('result.source_object', html)
        self.assertIn('/objects/', html)
        self.assertIn("playbooks/${actionTarget}/skill-drafts", html)
        self.assertIn('applySkillSuggestion(result.suggested_skills[0])', html)
        self.assertIn("action_create_skill_draft", html)
        self.assertIn("action_apply_authoring_pack", html)
        self.assertIn("editorActionButton('skills', skill.id, 'action_open_editor')", html)
        self.assertIn('async function putJson(path, payload)', html)
        self.assertIn('Promise.allSettled', html)
        self.assertIn('Partial API load failure', html)
        self.assertIn('saveEditorSelection()', html)
        self.assertIn("handleWorkbenchSubmit(handleTaskSubmit, event)", html)
        self.assertIn("handleWorkbenchSubmit(handleMcpServerSubmit, event)", html)
        self.assertIn('const apiBase = "/api";', html)
        self.assertIn('"artifacts": {"run_report": 4}', html)

    def test_dashboard_html_escapes_custom_api_base(self) -> None:
        html = build_dashboard_html({"goals": {}}, api_base='/api" onclick="alert(1)')

        self.assertIn("&quot; onclick=&quot;alert(1)", html)
        self.assertNotIn('<a class="endpoint-link" href="/api" onclick="alert(1)/goals"', html)


if __name__ == "__main__":
    unittest.main()
